from django.core.management.base import BaseCommand
from training.models import BrainArea, Phase, TrainingMethod, Artwork, UserProfile


BRAIN_AREAS = [
    ('V1', 'Corteza visual primaria', 'Polo occipital. Primera estación cortical. Detecta bordes, contraste, frecuencia espacial. Organizada retinotópicamente. En imaginería se activa ~15-30% vs visión real. Es el "lienzo" de la imagen mental.', 'Pantalla de resolución ultra-alta'),
    ('V2', 'Área visual secundaria', 'Rodea a V1. Primer nivel de integración. Agrupa bordes en objetos, asigna figura-fondo, detecta contornos ilusorios, estereopsis básica.', 'Programa de detección de bordes'),
    ('V3A', 'Área visual terciaria', 'Dorsal a V2. Infiere profundidad (perspectiva, gradiente textura, oclusión, disparidad). Shape-from-shading. Sensible a curvatura de superficies y movimiento coherente.', 'Motor de renderizado 3D'),
    ('V4', 'Área de color y forma compleja', 'Giro fusiforme. Color con constancia cromática, curvatura, textura, forma compleja. Responsable de que la imagen mental tenga color y textura.', 'Procesador de color y textura'),
    ('V5MT', 'Área temporal media (movimiento)', 'Surco temporal superior posterior. Detecta dirección de movimiento, velocidad, flujo óptico, movimiento ilusorio e implícito.', 'Detector de movimiento'),
    ('LOC', 'Lateral Occipital Complex', 'Corteza occipital lateral. Reconoce QUÉ ES un objeto comparando con representaciones almacenadas. Invariante a tamaño y posición.', 'Base de datos de objetos'),
    ('FFA', 'Fusiform Face Area', 'Giro fusiforme. Procesamiento especializado de rostros: identidad, expresión, configuración facial. Área más fácil de activar con imaginería.', 'Reconocimiento facial'),
    ('EBA', 'Extrastriate Body Area', 'Corteza occipito-temporal lateral. Procesamiento de cuerpos humanos, manos, posturas. Sensible a postura corporal.', 'Reconocimiento de cuerpos'),
    ('STS', 'Surco temporal superior', 'Percepción social: dirección de mirada, movimiento biológico, teoría de la mente. Alta activación con mirada directa.', 'Procesador social'),
    ('PPA', 'Parahippocampal Place Area', 'Giro parahipocampal. Procesamiento de escenas y lugares. Procesa estructura espacial (layout). Conecta con hipocampo para navegación.', 'GPS de lugares'),
    ('OPA', 'Occipital Place Area', 'Corteza occipital transversa. Procesamiento de escenas abiertas/exteriores, paisajes, horizontes.', 'Detector de paisajes'),
    ('IPS', 'Surco intraparietal', 'Modelo 3D del espacio, manipulación mental de objetos. Se activa durante rotación mental.', 'Motor de rotación 3D'),
    ('RETRO', 'Corteza retrosplenial', 'Orientación espacial, navegación mental. Se activa al imaginar recorrer un espacio.', 'Sistema de navegación'),
    ('AMIG', 'Amígdala', 'Procesamiento emocional, modulación de atención. Amplifica atención a imágenes con carga emocional. Las imágenes emocionalmente cargadas se retienen mejor.', 'Amplificador emocional'),
    ('PFC', 'Corteza prefrontal', 'Control top-down, atención voluntaria, working memory. Inicia y sostiene la imagen mental. Sin prefrontal activo la imagen se desvanece en 1-2s.', 'Director de orquesta'),
    ('PAR', 'Corteza parietal posterior', 'Mapa espacial, saliencia, tamaño relativo, working memory espacial. Parte de la vía dorsal.', 'Mapa espacial'),
]

PHASES = [
    {
        'number': 1,
        'title': 'Formas y colores sólidos',
        'objective': 'Registrar formas geométricas simples + color plano.\nCircuitos principales: V1 (orientación, bordes), V4 (color).',
        'protocol_instructions': '1. Mira la obra 30-60 segundos.\n2. Cierra ojos.\n3. Retiene: forma + color + posición.\n4. Cuando se desvanezca, abre ojos, recarga.\n5. Avanza cuando sostengas la imagen 10+ segundos.\n\nSemana 1-2: 10 min/día.',
        'circuits': ['V1', 'V4'],
    },
    {
        'number': 2,
        'title': 'Patrones repetitivos y postimagen',
        'objective': 'Activar construcción 3D ilusoria, postimagen geométrica, atención visual sostenida.\nCircuitos: V1 → V2 (agrupación) → V3/V3A (curvatura, profundidad) → IPS (objeto 3D).',
        'protocol_instructions': 'Misma base que Fase 1. Algunas obras requieren duración específica (Blaze máx 30s).\n\nSemana 1-2: 10 min/día.',
        'circuits': ['V1', 'V2', 'V3A', 'IPS'],
    },
    {
        'number': 3,
        'title': 'Objetos simples aislados',
        'objective': 'Visualizar objeto concreto con volumen, textura, iluminación.\nCircuitos: V4, LOC, corteza temporal inferior, V3A.',
        'protocol_instructions': '1. Mira la obra 30-60 segundos.\n2. Cierra ojos.\n3. Reconstruye: forma general primero, luego volumen, luego textura.\n4. Intenta "rotar" mentalmente el objeto (MET-3).\n5. Avanza cuando sostengas el objeto 15+ segundos con volumen.\n\nSemana 3-4: 15 min/día.',
        'circuits': ['V4', 'LOC', 'V3A'],
    },
    {
        'number': 4,
        'title': 'Espacios arquitectónicos',
        'objective': 'Construir espacio tridimensional con profundidad y luz direccional.\nCircuitos: V3A, PPA, surco intraparietal, corteza retrosplenial.',
        'protocol_instructions': '1. Mira la obra 60 segundos.\n2. Cierra ojos.\n3. Reconstruye: estructura del espacio (paredes, suelo, techo).\n4. Agrega luz: de dónde viene, dónde cae, dónde hay sombra.\n5. Intenta "caminar" mentalmente por el espacio.\n6. Avanza cuando puedas recorrer el espacio 20+ segundos.\n\nSemana 5-6: 15 min/día.',
        'circuits': ['V3A', 'PPA', 'IPS', 'RETRO'],
    },
    {
        'number': 5,
        'title': 'Formas orgánicas',
        'objective': 'Generar formas curvas, asimétricas, naturales, con movimiento o estructura biológica.\nCircuitos: V4 (curvatura compleja), corteza temporal inferior, V5/MT (movimiento implícito), FFA si hay rostros.',
        'protocol_instructions': 'Misma base de visualización + reconstrucción. Específico por obra.\n\nSemana 5-6: 15 min/día.',
        'circuits': ['V4', 'V5MT', 'FFA'],
    },
    {
        'number': 6,
        'title': 'Complejidad alta (escenas completas)',
        'objective': 'Reconstruir escena con múltiples elementos, texturas, iluminación compleja, atmósfera, narrativa.\nCircuitos: integración multi-área completa. Requiere circuito entrenado en fases 1-5.',
        'protocol_instructions': 'Visualización extendida 60s+. Reconstrucción multi-paso.\n\nSemana 7-8: 20 min/día.',
        'circuits': ['V1', 'V2', 'V3A', 'V4', 'V5MT', 'LOC', 'FFA', 'EBA', 'PPA', 'PFC'],
    },
]

METHODS = [
    {
        'code': 'MET-1',
        'name': 'Image Streaming (Win Wenger)',
        'protocol_steps': '1. Cierra los ojos.\n2. Observa lo que aparezca (aunque sea vago).\n3. Describe en voz alta con detalle: forma, color, textura, movimiento.\n4. No edites, no juzgues, solo describe.\n5. 10-20 min/sesión.\n\nMecanismo: verbalizar obliga al prefrontal a mantener la imagen activa.',
        'adaptation_flat_affect': 'FASE A (sem 3-4): Image Streaming perceptual. Describir solo lo que se VE (forma, color, textura, posición, movimiento, luz). NO pedir emociones.\n\nFASE B (sem 5-6): + detalle material. Agregar: "¿de qué material es?", "¿qué temperatura parece tener?", "¿es pesado o liviano?", "¿es rugoso o suave?"\n\nFASE C (sem 7-8): + noticing emocional. Agregar: "¿notas alguna reacción al ver esto?" Si dice "no noto nada" = válido. Si dice "noto algo pero no sé qué es" = progreso significativo.',
        'implementable_in_app': True,
    },
    {
        'code': 'MET-2',
        'name': 'Protocolo progresivo (aphantasia cure)',
        'protocol_steps': 'Nivel 1: Postimagen — mira objeto rojo 30s, cierra ojos, ve postimagen verde.\nNivel 2: Memoria inmediata — mira objeto simple 10s, cierra ojos, retiene.\nNivel 3: Memoria diferida — recuerda lugar conocido, recorre mentalmente.\nNivel 4: Construcción — imagina objeto que NO has visto.\nNivel 5: Manipulación — rota el objeto, cambia color, hazlo crecer.',
        'adaptation_flat_affect': 'Sin cambios en niveles 1-5. PRECAUCIÓN TEPT en Nivel 3: usar solo lugares ESPECÍFICOS, NEUTROS, ACTUALES. "Recorre la cocina donde estás viviendo ahora." NO "recuerda un lugar de tu infancia."',
        'implementable_in_app': False,
    },
    {
        'code': 'MET-3',
        'name': 'Rotación mental (Tetris mental)',
        'protocol_steps': 'Visualiza un objeto 3D simple (dado, silla, letra L).\nRótalo 90° mentalmente.\nRótalo otra vez.\nCambia eje de rotación.\n\nActiva V1, V2 y surco intraparietal.',
        'adaptation_flat_affect': 'Sin cambios. Puramente visuoespacial. IPS intacto.',
        'implementable_in_app': False,
    },
    {
        'code': 'MET-4',
        'name': 'Visualización dirigida (tradición tibetana)',
        'protocol_steps': '1. Mira imagen simple (círculo rojo) 1 min.\n2. Cierra ojos, reconstruye mentalmente.\n3. Cuando se desvanezca, abre ojos, recarga, repite.\n4. Progresa a imágenes más complejas.\n5. Objetivo: sostener imagen 5+ minutos con estabilidad.\n\nEvidencia: Kozhevnikov 2009 monjes tibetanos.',
        'adaptation_flat_affect': 'Sin cambios en protocolo básico. Versión estrictamente perceptual (retener forma, color, detalle). NO pedir devoción ni emoción.',
        'implementable_in_app': True,
    },
    {
        'code': 'MET-5',
        'name': 'Neurofeedback (asistido por tecnología)',
        'protocol_steps': 'EEG en áreas occipitales.\nSoftware detecta activación visual.\nFeedback auditivo/visual en tiempo real.\nSujeto aprende a modular voluntariamente.\n\nNo es inyección: sujeto genera, sistema solo informa.',
        'adaptation_flat_affect': 'Potencialmente muy útil. Puede: (1) confirmar que la amígdala responde aunque no se sienta, (2) entrenar modulación de inhibición prefrontal, (3) dar feedback objetivo independiente de emoción.',
        'implementable_in_app': False,
    },
]

# fmt: off
ARTWORKS = [
    # Phase 1
    {'catalog_id': 'F1-01', 'phase': 1, 'order_standard': 1, 'order_flat_affect': 1, 'artist': 'Kazimir Malevich', 'title': 'Black Square', 'year': '1915',
     'wikimedia_url': 'https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/6389/uploads/urunresimleri/buyuk/black-square-by-kazimir-malevich-as-ar-a66fe2.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V1', 'V2', 'PFC'],
     'training_purpose': 'Detección de bordes rectos. Contraste figura-fondo binario. Retención de forma mínima. Postimagen. Punto de partida.',
     'instructions_standard': 'Mira 30-60s. Cierra ojos. Retiene forma + color + posición. Abre ojos cuando se desvanezca. Avanza con 10+s.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F1-02', 'phase': 1, 'order_standard': 2, 'order_flat_affect': 2, 'artist': 'Kazimir Malevich', 'title': 'Suprematist Composition: White on White', 'year': '1918',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Kazimir_Malevich_-_%27Suprematist_Composition-_White_on_White%27%2C_oil_on_canvas%2C_1918%2C_Museum_of_Modern_Art.jpg/600px-Kazimir_Malevich_-_%27Suprematist_Composition-_White_on_White%27%2C_oil_on_canvas%2C_1918%2C_Museum_of_Modern_Art.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V1', 'V3A', 'PFC'],
     'training_purpose': 'Detección de bordes con bajo contraste. Rotación sutil. Atención a diferencias mínimas. Retención bajo ambigüedad.',
     'instructions_standard': 'Mira 30-60s. Cierra ojos. Retiene forma + color + posición.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F1-03', 'phase': 1, 'order_standard': 3, 'order_flat_affect': 3, 'artist': 'Kazimir Malevich', 'title': 'Eight Red Rectangles', 'year': '1915',
     'wikimedia_url': 'https://m.media-amazon.com/images/I/7159gKqX4aL._AC_UF1000,1000_QL80_.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V1', 'V2', 'V4', 'PAR', 'PFC'],
     'training_purpose': 'Distribución espacial múltiple (8 posiciones/orientaciones). Rotación múltiple. Agrupación por color. Memoria de configuración.',
     'instructions_standard': 'Mira 30-60s. Cierra ojos. Retiene 8 posiciones + orientaciones.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F1-04', 'phase': 1, 'order_standard': 4, 'order_flat_affect': 4, 'artist': 'Piet Mondrian', 'title': 'Composition with Red, Blue and Yellow', 'year': '1930',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Piet_Mondriaan%2C_1930_-_Mondrian_Composition_II_in_Red%2C_Blue%2C_and_Yellow.jpg/600px-Piet_Mondriaan%2C_1930_-_Mondrian_Composition_II_in_Red%2C_Blue%2C_and_Yellow.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V1', 'V2', 'V4', 'PAR'],
     'training_purpose': 'Segregación por color (3 primarios). Estructura de rejilla. Proporción y tamaño relativo. Composición como unidad. Añade V4 al circuito.',
     'instructions_standard': 'Mira 30-60s. Cierra ojos. Retiene colores + estructura rejilla + proporciones.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F1-05', 'phase': 1, 'order_standard': 5, 'order_flat_affect': 5, 'artist': 'Piet Mondrian', 'title': 'Composition II in Red, Blue, and Yellow', 'year': '1929',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Tableau_I%2C_by_Piet_Mondriaan.jpg/600px-Tableau_I%2C_by_Piet_Mondriaan.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V4', 'PAR', 'PFC'],
     'training_purpose': 'Retención de áreas amplias de color. Relación espacial simple. Variante más fácil que F1-04.',
     'instructions_standard': 'Mira 30-60s. Cierra ojos. Retiene bloques color + posiciones. Usar si F1-04 es difícil.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F1-06', 'phase': 1, 'order_standard': 6, 'order_flat_affect': 6, 'artist': 'Ellsworth Kelly', 'title': 'Red Blue Green', 'year': '1963',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/2/28/Kelly_%E2%80%93_Red_Blue_Green.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V1', 'V4', 'PFC'],
     'training_purpose': 'Color puro sin forma (aísla V4). Transiciones cromáticas abruptas. Retención de secuencia cromática.',
     'instructions_standard': 'Mira 30-60s. Cierra ojos. Retiene secuencia "rojo, azul, verde" izquierda→derecha.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F1-07', 'phase': 1, 'order_standard': 7, 'order_flat_affect': 7, 'artist': 'Ellsworth Kelly', 'title': 'Blue Green Red I', 'year': '1964',
     'wikimedia_url': '/static/img/Red-Green-Blue-by-Ellsworth-Kelly-1964-Material-Oil-on-canvas-Size-unframed-90-x.png',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V4'],
     'training_purpose': 'Curvatura simple + color. Transición borde recto → borde curvo. Puente hacia Fase 5.',
     'instructions_standard': 'Mira 30-60s. Cierra ojos. Retiene formas curvas + colores.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F1-08', 'phase': 1, 'order_standard': 8, 'order_flat_affect': 8, 'artist': 'Josef Albers', 'title': 'Homage to the Square', 'year': '1950-1960',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Josef_Albers%27_Studies_for_Homage_to_the_Square.jpg/600px-Josef_Albers%27_Studies_for_Homage_to_the_Square.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V2', 'V3A', 'V4', 'PFC'],
     'training_purpose': 'Interacción cromática (contraste simultáneo). Profundidad ilusoria por color. Concentricidad. Retención graduada. Única obra que entrena interacción cromática.',
     'instructions_standard': 'Mira 30-60s. Cierra ojos. Retiene de afuera hacia adentro (incremental).',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},

    # Phase 2
    {'catalog_id': 'F2-01', 'phase': 2, 'order_standard': 1, 'order_flat_affect': 1, 'artist': 'Victor Vasarely', 'title': 'Vega-Nor', 'year': '1969',
     'wikimedia_url': 'https://www.singulart.com/blog/wp-content/uploads/2024/02/Victor-Vasarely-Vega-Nor.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V2', 'V3A', 'IPS', 'PFC'],
     'training_purpose': 'Inferencia 3D desde distorsión 2D. Figura-fondo con volumen. Atención sostenida bajo inestabilidad. Postimagen 3D. Obra clave de Fase 2.',
     'instructions_standard': 'Mirar hasta que la esfera se estabilice. Cerrar ojos. Retener volumen 3D.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F2-02', 'phase': 2, 'order_standard': 2, 'order_flat_affect': 2, 'artist': 'Victor Vasarely', 'title': 'Zebegen', 'year': '1964',
     'wikimedia_url': 'https://www.prints.co.nz/mm5/graphics/00000001/1418_Zebegen_Vasarely_Victor.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V3A', 'V4', 'PAR'],
     'training_purpose': 'Múltiples objetos 3D simultáneos. Textura sobre superficie curva (rayas cebra). Sombras y anclaje espacial.',
     'instructions_standard': 'Mirar. Cerrar ojos. Retener múltiples esferas con textura.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F2-03', 'phase': 2, 'order_standard': 3, 'order_flat_affect': 3, 'artist': 'Bridget Riley', 'title': 'Movement in Squares', 'year': '1961',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/en/1/1b/Riley%2C_Movement_in_Squares.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V1', 'V5MT'],
     'training_purpose': 'Postimagen de alto contraste (la más fuerte del catálogo). Movimiento ilusorio. Gradiente espacial. Recomendada para EMPEZAR Fase 2.',
     'instructions_standard': 'Mirar 30-60s (máximo contraste). Cerrar ojos. Postimagen potente. Usar para MET-2 Nivel 1.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F2-04', 'phase': 2, 'order_standard': 4, 'order_flat_affect': 4, 'artist': 'Bridget Riley', 'title': 'Fall', 'year': '1963',
     'wikimedia_url': 'https://media.tate.org.uk/art/images/work/T/T00/T00616_9.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V1', 'V4', 'V5MT'],
     'training_purpose': 'Curvatura repetitiva. Movimiento direccional ilusorio. Ritmo visual. Puente Fase 1 (rectas) a Fase 5 (curvas orgánicas).',
     'instructions_standard': 'Mirar. Observar movimiento descendente. Cerrar ojos. Retener ondulación + movimiento.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F2-05', 'phase': 2, 'order_standard': 5, 'order_flat_affect': 5, 'artist': 'Bridget Riley', 'title': 'Blaze', 'year': '1964',
     'wikimedia_url': 'https://d7hftxdivxxvm.cloudfront.net/?height=1912&quality=80&resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FRkVf05cQRyyK5nWo5s8z1w%2Flarge.jpg&width=1919',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V3A', 'V5MT'],
     'training_purpose': 'Rotación ilusoria (única obra con este efecto). Expansión/contracción. Vértigo perceptual controlado. Máx activación V5/MT.',
     'instructions_standard': 'Mirar máx 30s (epileptógeno). Cerrar ojos. Retener espiral + sensación rotacional.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F2-06', 'phase': 2, 'order_standard': 6, 'order_flat_affect': 6, 'artist': 'M.C. Escher', 'title': 'Sky and Water I', 'year': '1938',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/en/4/4c/Sky_and_Water_I.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V1', 'V2', 'LOC'],
     'training_purpose': 'Metamorfosis perceptual (pájaro→ambiguo→pez). Percepción biestable. Teselación. Inversión figura-fondo.',
     'instructions_standard': 'Mirar centrando en zona de transición. Cerrar ojos. Retener ambas interpretaciones.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F2-07', 'phase': 2, 'order_standard': 7, 'order_flat_affect': 7, 'artist': 'M.C. Escher', 'title': 'Circle Limit III', 'year': '1959',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/en/5/55/Escher_Circle_Limit_III.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V1', 'V2', 'V3A', 'PAR'],
     'training_purpose': 'Escalamiento logarítmico. Espacio no euclidiano. Simetría rotacional compleja. Profundidad por tamaño.',
     'instructions_standard': 'Mirar contemplando decrecimiento hacia bordes. Cerrar ojos. Retener estructura escalada.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},

    # Phase 3
    {'catalog_id': 'F3-01', 'phase': 3, 'order_standard': 1, 'order_flat_affect': 3, 'artist': 'Francisco de Zurbarán', 'title': 'Still Life with Lemons, Oranges and a Rose', 'year': '1633',
     'wikimedia_url': 'https://m.media-amazon.com/images/I/61dNcxqSmAL._AC_UF1000,1000_QL80_.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V2', 'V3A', 'V4', 'LOC'],
     'training_purpose': 'Segmentación en bloques. Iluminación lateral dramática (shape-from-shading). Textura de superficie (3 texturas). Color naturalista saturado. Fondo negro aislamiento.',
     'instructions_standard': 'Mira 30-60s. Cierra ojos. Forma general primero, luego volumen, luego textura. Retener un grupo a la vez, luego combinar.',
     'instructions_flat_affect': 'Mira la obra. Observa las formas, los colores, la luz. Cierra ojos. Reconstruye: estructura general → textura → color → luz.',
     'reexposure_prompt': ''},
    {'catalog_id': 'F3-02', 'phase': 3, 'order_standard': 2, 'order_flat_affect': 5, 'artist': 'Francisco de Zurbarán', 'title': 'Agnus Dei', 'year': '1635-1640',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Francisco_de_Zurbar%C3%A1n_006.jpg/1280px-Francisco_de_Zurbar%C3%A1n_006.jpg',
     'emotional_category': 'B', 'emotional_intensity_level': 1,
     'brain_areas': ['V3A', 'V4', 'LOC', 'AMIG'],
     'training_purpose': 'Objeto único forma orgánica. Textura orgánica (lana). Volumen por sombra suave. Carga emocional leve (facilitador). Estímulo más fácil de Fase 3: 1 objeto, fondo negro.',
     'instructions_standard': 'Mira 30-60s. Cierra ojos. Forma general → volumen → textura. Rotar mentalmente.',
     'instructions_flat_affect': 'Mira la obra. Observa las formas, los colores, la luz. Cierra ojos. Reconstruye: estructura general → textura → color → luz. NO observar emociones.',
     'reexposure_prompt': '¿Notas algo más aparte de la forma?'},
    {'catalog_id': 'F3-03', 'phase': 3, 'order_standard': 3, 'order_flat_affect': 4, 'artist': 'Giorgio Morandi', 'title': 'Natura Morta', 'year': '1956',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/en/6/67/%27Natura_Morta%27%2C_oil_on_canvas_painting_by_Giorgio_Morandi%2C_1956%2C_private_collection.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V2', 'V3A', 'V4', 'LOC'],
     'training_purpose': 'Discriminación tonal fina (tonos cercanos). Agrupación de objetos como unidad. Volumen cilíndrico. Espacio negativo entre objetos.',
     'instructions_standard': 'Mira 30-60s. Cierra ojos. Reconstruye discriminando tonos similares.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F3-04', 'phase': 3, 'order_standard': 4, 'order_flat_affect': 1, 'artist': 'Giorgio Morandi', 'title': 'Still Life', 'year': '1946',
     'wikimedia_url': 'https://media.tate.org.uk/art/images/work/N/N05/N05782_10.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V1', 'V2'],
     'training_purpose': 'Jerarquía de luminosidad. Oclusión parcial (completar forma oculta). Inferencia de "lo que no se ve". Más fácil que F3-03 por mayor contraste.',
     'instructions_standard': 'Mira 30-60s. Cierra ojos. Reconstruye incluyendo formas ocultas por oclusión.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F3-05', 'phase': 3, 'order_standard': 5, 'order_flat_affect': 2, 'artist': 'Jean-Baptiste-Siméon Chardin', 'title': 'The Silver Goblet', 'year': '~1728',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Jean-Sim%C3%A9on_Chardin_%28French_-_Still_Life_with_Peaches%2C_a_Silver_Goblet%2C_Grapes%2C_and_Walnuts_-_Google_Art_Project.jpg/600px-Jean-Sim%C3%A9on_Chardin_%28French_-_Still_Life_with_Peaches%2C_a_Silver_Goblet%2C_Grapes%2C_and_Walnuts_-_Google_Art_Project.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V3A', 'V4', 'PAR'],
     'training_purpose': 'Reflejo especular (metal). Contraste de materiales. Composición mínima asimétrica. Iluminación naturalista suave. Único estímulo con metal reflectante.',
     'instructions_standard': 'Mira 30-60s. Cierra ojos. Reconstruye: forma → volumen → textura → reflexión.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},

    # Phase 4
    {'catalog_id': 'F4-01', 'phase': 4, 'order_standard': 1, 'order_flat_affect': 1, 'artist': 'Edward Hopper', 'title': 'Sun in an Empty Room', 'year': '1963',
     'wikimedia_url': 'https://www.edwardhopper.net/assets/img/paintings/sun-in-an-empty-room.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V1', 'V3A', 'PPA', 'RETRO', 'PFC'],
     'training_purpose': 'Espacio vacío como objeto (estímulo PPA más puro). Luz como única información. Geometría de proyección. Navegación mental. Recomendada para EMPEZAR Fase 4.',
     'instructions_standard': 'Mira 60s. Cierra ojos. Estructura espacio (paredes, suelo). Agrega luz (origen, caída, sombra). Intenta "caminar" mentalmente. Avanza con 20+s.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F4-02', 'phase': 4, 'order_standard': 2, 'order_flat_affect': 2, 'artist': 'Edward Hopper', 'title': 'Rooms by the Sea', 'year': '1951',
     'wikimedia_url': 'https://www.edwardhopper.net/assets/img/paintings/rooms-by-the-sea.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 1,
     'brain_areas': ['V3A', 'PPA', 'OPA', 'PFC', 'PAR'],
     'training_purpose': 'Transición interior-exterior. Profundidad extrema (metros + kilómetros). Luz rebotada. Incongruencia espacial productiva.',
     'instructions_standard': 'Mira 60s. Cierra ojos. Estructura espacio interior + mar. Agrega dos escalas profundidad. Caminar mentalmente.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F4-03', 'phase': 4, 'order_standard': 3, 'order_flat_affect': 5, 'artist': 'Edward Hopper', 'title': 'Morning Sun', 'year': '1952',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/9/95/Edward_Hopper_-_Morning_Sun_-_c_1952_-_Columbus_Museum_of_Art.jpg',
     'emotional_category': 'B', 'emotional_intensity_level': 2,
     'brain_areas': ['FFA', 'EBA', 'PPA', 'STS', 'V3A', 'AMIG', 'PFC'],
     'training_purpose': 'Figura humana en espacio (primera del catálogo). Dirección de mirada. Estado emocional por postura. Luz como narrativa. Activa FFA/EBA/STS.',
     'instructions_standard': 'Mira 60s. Cierra ojos. Estructura espacio + figura + mirada + luz. Solo cuando F4-01/F4-02 sean fáciles.',
     'instructions_flat_affect': 'Mira la obra. Observa la geometría del espacio, la posición de la figura, la dirección de la luz. Cierra ojos. Reconstruye: espacio → figura → luz.',
     'reexposure_prompt': '¿La postura de la figura te produce algo?'},
    {'catalog_id': 'F4-04', 'phase': 4, 'order_standard': 4, 'order_flat_affect': 6, 'artist': 'Giorgio de Chirico', 'title': 'Mystery and Melancholy of a Street', 'year': '1914',
     'wikimedia_url': 'https://uploads2.wikiart.org/images/giorgio-de-chirico/mystery-and-melancholy-of-a-street-1914.jpg!Large.jpg',
     'emotional_category': 'C', 'emotional_intensity_level': 3,
     'brain_areas': ['V2', 'V3A', 'LOC', 'PAR', 'AMIG', 'PFC'],
     'training_purpose': 'Perspectiva lineal extrema. Sombra como objeto (representar lo ausente). Tensión narrativa espacial. Mayor carga emocional de Fase 4.',
     'instructions_standard': 'Mira 60s. Cierra ojos. Perspectiva + sombra + figuras. Recorrer arcadas mentalmente.',
     'instructions_flat_affect': 'Mira la obra. Observa las líneas de perspectiva, la geometría de las arcadas, la posición de la sombra. Cierra ojos. Reconstruye: perspectiva → arcadas → sombra.',
     'reexposure_prompt': '¿La sombra te produce algo?'},
    {'catalog_id': 'F4-05', 'phase': 4, 'order_standard': 5, 'order_flat_affect': 3, 'artist': 'Giorgio de Chirico', 'title': 'The Enigma of the Hour', 'year': '1911',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/en/6/68/The_Enigma_of_the_Hour.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V2', 'V3A', 'PPA', 'PFC'],
     'training_purpose': 'Arquitectura simétrica (retener mitad y espejear). Elemento focal central (reloj). Profundidad por oclusión. Temporalidad visual. Más fácil que F4-04.',
     'instructions_standard': 'Mira 60s. Cierra ojos. Empezar por reloj central, expandir simétricamente.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F4-06', 'phase': 4, 'order_standard': 6, 'order_flat_affect': 4, 'artist': 'Giorgio de Chirico', 'title': 'Piazza d\'Italia (serie)', 'year': 'múltiples',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/en/b/b2/The_Red_Tower_by_Giorgio_de_Chirico.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V3A', 'V4', 'LOC', 'PPA', 'OPA', 'PAR'],
     'training_purpose': 'Espacio abierto grande (activa OPA más que PPA). Múltiples fuentes de profundidad integradas. Relación objeto-en-lugar. Atmósfera cromática.',
     'instructions_standard': 'Mira 60s. Cierra ojos. Estructura espacio abierto. Posicionar objetos (estatuas, torres). Agregar atmósfera cromática.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},

    # Phase 5
    {'catalog_id': 'F5-01', 'phase': 5, 'order_standard': 1, 'order_flat_affect': 2, 'artist': 'Katsushika Hokusai', 'title': 'The Great Wave off Kanagawa', 'year': '1831',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Tsunami_by_hokusai_19th_century.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 1,
     'brain_areas': ['V1', 'V2', 'V3A', 'V4', 'V5MT', 'PAR', 'AMIG'],
     'training_purpose': 'Curvatura orgánica dominante. Movimiento congelado. Fractalidad espuma. Tensión por escala. Profundidad por capas (3 planos). Máx dinámica en Fase 5.',
     'instructions_standard': 'Mirar. Cerrar ojos. Retener curva ola + espuma + profundidad 3 planos.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F5-02', 'phase': 5, 'order_standard': 2, 'order_flat_affect': 1, 'artist': 'Katsushika Hokusai', 'title': 'South Wind, Clear Sky (Red Fuji)', 'year': '1831',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/5/57/Red_Fuji_southern_wind_clear_morning.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V3A', 'V4', 'PPA', 'OPA'],
     'training_purpose': 'Curva simple monumental. Dos zonas cromáticas. Horizonte y escala planetaria. Recomendada para EMPEZAR Fase 5.',
     'instructions_standard': 'Mirar. Cerrar ojos. Retener curva montaña + 2 colores + horizonte.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F5-03', 'phase': 5, 'order_standard': 3, 'order_flat_affect': 4, 'artist': 'Georgia O\'Keeffe', 'title': 'Jimson Weed/White Flower No. 1', 'year': '1932',
     'wikimedia_url': 'https://elephant.art/wp-content/uploads/2018/11/OKeeffe_Jimson-Weed-White-Flower-No-1.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V2', 'V4', 'PAR'],
     'training_purpose': 'Simetría radial orgánica. Gradientes suaves. Escala ambigua. Blanco con variaciones sutiles. Estructura centrípeta. Ideal transición geometría→naturaleza.',
     'instructions_standard': 'Mirar. Cerrar ojos. Empezar por centro de la flor, expandir pétalos.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F5-04', 'phase': 5, 'order_standard': 4, 'order_flat_affect': 5, 'artist': 'Georgia O\'Keeffe', 'title': 'Red Canna', 'year': '~1924',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Georgia_O%27Keeffe_Red_Canna_1919_HMA.jpg/500px-Georgia_O%27Keeffe_Red_Canna_1919_HMA.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V3A', 'V4', 'PAR', 'PFC'],
     'training_purpose': 'Envolvimiento espacial. Color saturado cálido dominante. Ritmo orgánico. Intimidad de escala.',
     'instructions_standard': 'Mirar. Cerrar ojos. Retener envolvimiento + rojo saturado + pliegues.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F5-05', 'phase': 5, 'order_standard': 5, 'order_flat_affect': 6, 'artist': 'Georgia O\'Keeffe', 'title': 'Black Iris', 'year': '1926',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/en/b/b7/Georgia_O%27Keeffe%2C_Black_Iris%2C_1926%2C_Metropolitan_Museum_of_Art.jpg',
     'emotional_category': 'B', 'emotional_intensity_level': 1,
     'brain_areas': ['V2', 'V3A', 'V4', 'LOC', 'PFC'],
     'training_purpose': 'Apertura centrífuga. Gradiente cromático continuo. Profundidad por superposición pétalos. Ambigüedad figurativa. Mayor ambigüedad de Fase 5.',
     'instructions_standard': 'Mirar. Cerrar ojos. Retener apertura desde centro + gradiente color + capas pétalos.',
     'instructions_flat_affect': 'Mira la obra. Observa las formas curvas, el gradiente de color, las capas de pétalos. Cierra ojos. Reconstruye: centro → pétalos → gradiente.',
     'reexposure_prompt': ''},
    {'catalog_id': 'F5-06', 'phase': 5, 'order_standard': 6, 'order_flat_affect': 3, 'artist': 'Hilma af Klint', 'title': 'The Ten Largest, No. 7', 'year': '1907',
     'wikimedia_url': 'https://www.guggenheim.org/wp-content/uploads/2017/08/art-hilma-af-klint-ten-largest-no-7-adulthood-group-iv-X.2017.603-1.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V4', 'PPA', 'OPA', 'PAR'],
     'training_purpose': 'Híbrido orgánico-geométrico. Colores planos en formas curvas. Composición descentralizada. Escala monumental. Puente Fase 1-Fase 5.',
     'instructions_standard': 'Mirar. Cerrar ojos. Retener distribución de formas orgánicas + colores planos. Recorrer obra.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},

    # Phase 6
    {'catalog_id': 'F6-01', 'phase': 6, 'order_standard': 1, 'order_flat_affect': 6, 'artist': 'Johannes Vermeer', 'title': 'Girl with a Pearl Earring', 'year': '1665',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Meisje_met_de_parel.jpg/600px-Meisje_met_de_parel.jpg',
     'emotional_category': 'C', 'emotional_intensity_level': 3,
     'brain_areas': ['V1', 'V2', 'V3A', 'V4', 'FFA', 'STS', 'AMIG', 'PFC'],
     'training_purpose': 'Procesamiento facial completo. Mirada directa. Iluminación Rembrandt. Material especular (perla). Aislamiento fondo negro. Expresión emocional ambigua. Recomendada para EMPEZAR Fase 6 (modo estándar).',
     'instructions_standard': 'Mira 60+s. Cierra ojos. Retener rostro + mirada + luz + perla. 20+s para avanzar.',
     'instructions_flat_affect': 'Mira la obra. Observa la geometría del rostro, el volumen dado por la iluminación, el punto de luz de la perla, el contraste con el fondo. Cierra ojos. Reconstruye: volumen rostro → luz → perla → fondo.',
     'reexposure_prompt': '¿La mirada te produce algo?'},
    {'catalog_id': 'F6-02', 'phase': 6, 'order_standard': 2, 'order_flat_affect': 1, 'artist': 'Johannes Vermeer', 'title': 'The Milkmaid', 'year': '1658',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg/600px-Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg',
     'emotional_category': 'B', 'emotional_intensity_level': 2,
     'brain_areas': ['V1', 'V3A', 'V4', 'V5MT', 'FFA', 'EBA', 'LOC', 'PPA', 'PFC'],
     'training_purpose': 'Escena narrativa acción (primera con acción en curso). Múltiples texturas (7+, máx catálogo). Líquido en movimiento. Iluminación ventana. Composición piramidal.',
     'instructions_standard': 'Mira 60+s. Cierra ojos. Retener acción + texturas + chorro leche + iluminación completa. Solo cuando F6-01 se sostenga 20+s.',
     'instructions_flat_affect': 'Mira la obra. Observa la acción (vertido), las texturas (pan, cerámica, tela, metal, leche), la iluminación lateral. Cierra ojos. Reconstruye: acción → texturas → iluminación.',
     'reexposure_prompt': ''},
    {'catalog_id': 'F6-03', 'phase': 6, 'order_standard': 3, 'order_flat_affect': 2, 'artist': 'Johannes Vermeer', 'title': 'The Art of Painting', 'year': '1666',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Jan_Vermeer_-_The_Art_of_Painting_-_Google_Art_Project.jpg/600px-Jan_Vermeer_-_The_Art_of_Painting_-_Google_Art_Project.jpg',
     'emotional_category': 'B', 'emotional_intensity_level': 2,
     'brain_areas': ['V2', 'V3A', 'V4', 'PPA', 'PAR', 'PFC'],
     'training_purpose': 'Recursividad visual (pintor pintando pintura). Perspectiva baldosas. Cortina como plano entrada. 5+ planos profundidad (máx catálogo). Máx complejidad del catálogo.',
     'instructions_standard': 'Mira 60+s. Cierra ojos. Retener cortina + pintor + modelo + mapa + baldosas + profundidad. 30+s = circuito completamente funcional.',
     'instructions_flat_affect': 'Mira la obra. Observa los planos de profundidad (cortina → pintor → modelo → mapa → pared), las baldosas en perspectiva, los materiales. Cierra ojos. Reconstruye: cortina → pintor → modelo → mapa → baldosas.',
     'reexposure_prompt': ''},
    {'catalog_id': 'F6-04', 'phase': 6, 'order_standard': 4, 'order_flat_affect': 4, 'artist': 'J.M.W. Turner', 'title': 'Rain, Steam and Speed', 'year': '1844',
     'wikimedia_url': 'https://www.nationalgallery.org.uk/media/00ebeihn/n-0538-00-000091-xl-hd.jpg?rxy=0.6523517382413088,0.6219178082191781&width=1280&height=960&v=1dbcbdcdcb22e30',
     'emotional_category': 'A', 'emotional_intensity_level': 0,
     'brain_areas': ['V1', 'V2', 'V4', 'V5MT'],
     'training_purpose': 'Imaginería sin bordes definidos. Atmósfera como contenido. Movimiento por blur direccional. Gradientes de visibilidad. Crítica para desentrenar expectativa de nitidez.',
     'instructions_standard': 'Mira 60+s. Cierra ojos. Retener atmósfera + movimiento + borrosidad + formas emergentes.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
    {'catalog_id': 'F6-05', 'phase': 6, 'order_standard': 5, 'order_flat_affect': 3, 'artist': 'J.M.W. Turner', 'title': 'The Fighting Temeraire', 'year': '1839',
     'wikimedia_url': 'https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/1-the-fighting-temeraire-william-turner.jpg',
     'emotional_category': 'B', 'emotional_intensity_level': 2,
     'brain_areas': ['V3A', 'V4', 'LOC', 'PFC'],
     'training_purpose': 'Gradiente cromático atmosférico completo (azul→naranja→rojo→amarillo). Reflejo en agua. Narrativa temporal. Dos focos contrastantes. Puente entre nitidez Vermeer y abstracción F6-06.',
     'instructions_standard': 'Mira 60+s. Cierra ojos. Retener gradiente cielo + reflejo agua + 2 barcos contrastantes.',
     'instructions_flat_affect': 'Mira la obra. Observa el gradiente de color del cielo, el reflejo en el agua, los dos barcos contrastantes. Cierra ojos. Reconstruye: gradiente → reflejo → barcos.',
     'reexposure_prompt': '¿El atardecer te produce algo?'},
    {'catalog_id': 'F6-06', 'phase': 6, 'order_standard': 6, 'order_flat_affect': 5, 'artist': 'J.M.W. Turner', 'title': 'Snow Storm — Steam-Boat off a Harbour\'s Mouth', 'year': '1842',
     'wikimedia_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Joseph_Mallord_William_Turner_-_Snow_Storm_-_Steam-Boat_off_a_Harbour%27s_Mouth_-_WGA23178.jpg/1280px-Joseph_Mallord_William_Turner_-_Snow_Storm_-_Steam-Boat_off_a_Harbour%27s_Mouth_-_WGA23178.jpg',
     'emotional_category': 'A', 'emotional_intensity_level': 3,
     'brain_areas': ['V4', 'V5MT', 'PPA', 'OPA', 'PFC'],
     'training_purpose': 'Estructura vorticial (máx V5/MT rotacional). Imaginería sin objeto. Inmersión total. Límites de la representación. Máx abstracción del catálogo. Nivel máximo.',
     'instructions_standard': 'Mira 60+s. Cierra ojos. Retener EXPERIENCIA: movimiento, color, envolvimiento, incertidumbre. No intentar "ver" un objeto.',
     'instructions_flat_affect': '', 'reexposure_prompt': ''},
]
# fmt: on


class Command(BaseCommand):
    help = 'Puebla la base de datos con las 35 obras, fases, métodos y áreas cerebrales'

    def handle(self, *args, **options):
        self.stdout.write('Creando áreas cerebrales...')
        area_map = {}
        for code, name, desc, analogy in BRAIN_AREAS:
            obj, _ = BrainArea.objects.update_or_create(
                code=code, defaults={'name': name, 'description': desc, 'analogy': analogy}
            )
            area_map[code] = obj
        self.stdout.write(self.style.SUCCESS(f'  {len(area_map)} áreas creadas'))

        self.stdout.write('Creando fases...')
        phase_map = {}
        for p in PHASES:
            obj, _ = Phase.objects.update_or_create(
                number=p['number'],
                defaults={
                    'title': p['title'],
                    'objective': p['objective'],
                    'protocol_instructions': p['protocol_instructions'],
                },
            )
            obj.primary_circuits.set([area_map[c] for c in p['circuits'] if c in area_map])
            phase_map[p['number']] = obj
        self.stdout.write(self.style.SUCCESS(f'  {len(phase_map)} fases creadas'))

        self.stdout.write('Creando métodos...')
        for m in METHODS:
            TrainingMethod.objects.update_or_create(
                code=m['code'],
                defaults={
                    'name': m['name'],
                    'protocol_steps': m['protocol_steps'],
                    'adaptation_flat_affect': m['adaptation_flat_affect'],
                    'implementable_in_app': m['implementable_in_app'],
                },
            )
        self.stdout.write(self.style.SUCCESS(f'  {len(METHODS)} métodos creados'))

        self.stdout.write('Creando obras...')
        for a in ARTWORKS:
            obj, _ = Artwork.objects.update_or_create(
                catalog_id=a['catalog_id'],
                defaults={
                    'phase': phase_map[a['phase']],
                    'order_standard': a['order_standard'],
                    'order_flat_affect': a.get('order_flat_affect', a['order_standard']),
                    'artist': a['artist'],
                    'title': a['title'],
                    'year': a['year'],
                    'wikimedia_url': a['wikimedia_url'],
                    'emotional_category': a['emotional_category'],
                    'emotional_intensity_level': a['emotional_intensity_level'],
                    'training_purpose': a['training_purpose'],
                    'instructions_standard': a['instructions_standard'],
                    'instructions_flat_affect': a.get('instructions_flat_affect', ''),
                    'reexposure_prompt': a.get('reexposure_prompt', ''),
                },
            )
            areas = [area_map[c] for c in a['brain_areas'] if c in area_map]
            obj.brain_areas.set(areas)
        self.stdout.write(self.style.SUCCESS(f'  {len(ARTWORKS)} obras creadas'))

        self.stdout.write('Creando perfil de usuario...')
        UserProfile.objects.get_or_create(pk=1)
        self.stdout.write(self.style.SUCCESS('  Perfil creado'))

        self.stdout.write(self.style.SUCCESS('\nSeed completado.'))
