# Generated by Django 6.0.3 on 2026-03-12 17:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrainArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('analogy', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FieldCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_type', models.CharField(choices=[('FFA', 'Rostro (FFA)'), ('EBA', 'Cuerpo (EBA)'), ('PPA', 'Lugar (PPA)'), ('OPA', 'Escena abierta (OPA)'), ('NAV', 'Navegación'), ('OBJ', 'Objeto (LOC)'), ('COLOR', 'Color (V4)'), ('MOTION', 'Movimiento (V5/MT)'), ('MULTI', 'Integración múltiple'), ('OTHER', 'Otro')], max_length=10)),
                ('quality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField()),
                ('eyes_open', models.BooleanField(default=True)),
                ('in_motion', models.BooleanField(default=False)),
                ('deliberate', models.BooleanField(default=True)),
                ('immediate_retention', models.BooleanField(default=True)),
                ('session_end_retention', models.BooleanField(blank=True, null=True)),
                ('next_day_retention', models.BooleanField(blank=True, null=True)),
                ('repetition_count', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('protocol_steps', models.TextField()),
                ('adaptation_flat_affect', models.TextField(blank=True, default='')),
                ('implementable_in_app', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VVIQResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(80)])),
                ('item_scores', models.JSONField(default=dict)),
                ('context', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('title', models.CharField(max_length=200)),
                ('objective', models.TextField()),
                ('protocol_instructions', models.TextField(blank=True, default='')),
                ('primary_circuits', models.ManyToManyField(blank=True, related_name='phases', to='training.brainarea')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.CharField(max_length=10, unique=True)),
                ('order_standard', models.PositiveSmallIntegerField()),
                ('order_flat_affect', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=50)),
                ('wikimedia_url', models.URLField(max_length=500)),
                ('emotional_category', models.CharField(choices=[('A', 'Cat A — Sin dependencia emocional'), ('B', 'Cat B — Dependencia parcial'), ('C', 'Cat C — Alta dependencia emocional')], default='A', max_length=1)),
                ('training_purpose', models.TextField(blank=True, default='')),
                ('instructions_standard', models.TextField(blank=True, default='')),
                ('instructions_flat_affect', models.TextField(blank=True, default='')),
                ('emotional_intensity_level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('reexposure_prompt', models.TextField(blank=True, default='')),
                ('brain_areas', models.ManyToManyField(blank=True, related_name='artworks', to='training.brainarea')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='training.phase')),
            ],
            options={
                'ordering': ['phase__number', 'order_standard'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('standard', 'Sesión estándar'), ('image_streaming', 'Image Streaming'), ('free', 'Práctica libre')], default='standard', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('viewing_duration', models.PositiveIntegerField(default=0, help_text='Segundos de visualización')),
                ('retention_duration', models.PositiveIntegerField(default=0, help_text='Segundos de retención')),
                ('vividness_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('stability_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('detail_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('emotional_response', models.TextField(blank=True, default='')),
                ('emotional_indicator_detected', models.BooleanField(default=False)),
                ('prosody_change_noted', models.BooleanField(default=False)),
                ('body_reaction_noted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.artwork')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('standard', 'Estándar'), ('flat_affect', 'Flat Affect (TEPT)')], default='standard', max_length=20)),
                ('program_start_date', models.DateField(blank=True, null=True)),
                ('vviq_baseline', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.phase')),
            ],
        ),
    ]
