# Generated by Django 6.0.3 on 2026-03-14 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('glyph', models.CharField(max_length=10)),
                ('geometric_form', models.CharField(choices=[('CIRCLE', 'Círculo'), ('CROSS', 'Cruz'), ('TRIANGLE', 'Triángulo'), ('SQUARE', 'Cuadrado'), ('OTHER', 'Otro')], default='OTHER', max_length=10)),
                ('nesting_level', models.PositiveSmallIntegerField(default=0, help_text='0=simple, 1=anidado')),
                ('primary_meaning', models.CharField(max_length=200)),
                ('additional_meanings', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fieldcapture',
            name='bounding_boxes_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fieldcapture',
            name='composition_layer_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldcapture',
            name='readback_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldcapture',
            name='text_content',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='fieldcapture',
            name='text_format',
            field=models.CharField(blank=True, choices=[('calligraphy', 'Caligrafía'), ('typographic', 'Tipográfico')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldcapture',
            name='capture_type',
            field=models.CharField(choices=[('FFA', 'Rostro (FFA)'), ('EBA', 'Cuerpo (EBA)'), ('PPA', 'Lugar (PPA)'), ('OPA', 'Escena abierta (OPA)'), ('NAV', 'Navegación'), ('OBJ', 'Objeto (LOC)'), ('COLOR', 'Color (V4)'), ('MOTION', 'Movimiento (V5/MT)'), ('MULTI', 'Integración múltiple'), ('TEXT', 'Texto (VWFA)'), ('COMP', 'Composición multi-fuente'), ('ANNOT', 'Anotación (bbox)'), ('SYMBOL', 'Símbolo'), ('OTHER', 'Otro')], max_length=10),
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CAPTURE', 'Captura'), ('PROJECTION', 'Proyección'), ('COMPOSITION', 'Composición'), ('ANNOTATION', 'Anotación'), ('CONTROL', 'Control'), ('RETENTION', 'Retención')], max_length=15)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('partial', 'Parcial'), ('not_yet', 'No adquirida')], default='not_yet', max_length=10)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('brain_areas', models.ManyToManyField(blank=True, related_name='capabilities', to='training.brainarea')),
            ],
            options={
                'verbose_name_plural': 'capabilities',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.AddField(
            model_name='fieldcapture',
            name='symbols_used',
            field=models.ManyToManyField(blank=True, related_name='field_captures', to='training.symbol'),
        ),
        migrations.CreateModel(
            name='WorkspaceExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('TEXT', 'Proyección de texto'), ('COMP', 'Composición multi-fuente'), ('ANNOT', 'Anotación (bbox)'), ('SYMBOL', 'Símbolo'), ('FULL', 'Workspace completo')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duración en segundos')),
                ('text_content', models.TextField(blank=True, default='')),
                ('text_format', models.CharField(blank=True, choices=[('calligraphy', 'Caligrafía'), ('typographic', 'Tipográfico')], default='', max_length=20)),
                ('text_original_composition', models.BooleanField(default=False)),
                ('readback_success', models.BooleanField(blank=True, null=True)),
                ('layer_count', models.PositiveSmallIntegerField(default=0)),
                ('degradation_noted', models.BooleanField(default=False)),
                ('annotation_count', models.PositiveSmallIntegerField(default=0)),
                ('bounding_boxes_used', models.BooleanField(default=False)),
                ('vividness_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('stability_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('detail_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('semantic_clarity', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('sources_used', models.ManyToManyField(blank=True, related_name='workspace_exercises', to='training.brainarea')),
                ('symbols_used', models.ManyToManyField(blank=True, related_name='workspace_exercises', to='training.symbol')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
